# Generated by Django 4.2.17 on 2025-01-15 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='events/videos/'),
        ),
    ]
